language: ruby
cache: bundler
rvm:
 - "2.1.5"

addons:
  postgresql: "9.3"

services:
  - postgresql
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - cd railsapp
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:test:prepare
install: true
script:
  - bin/rspec
  - bin/cucumber
